name: cars
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Car.png
    - assets/View 1.png
    - assets/View 2.png
    - assets/View 3.png
    - assets/View 5.png
    - assets/View 6.png
    - assets/normal.png
    - assets/vip.png
    - assets/vipseller.png
    - assets/login screen (2).png
    - assets/Sign Up Screen (1).png
    - assets/OTP (1).png
    - assets/Choose Role (1).png
    - assets/pexels-garvin-st-villier-3311574 1.png

     # Normal home brand images
    - assets/home/image.png
    - assets/home/hyundai.png
    - assets/home/image-1.png
    - assets/home/image-2.png
    - assets/home/image-3.png
    - assets/home/image-4.png
    - assets/home/image-5.png
    - assets/home/image-6.png
    - assets/home/image 12.png
    
    # VIP home brand images
    - assets/viphome/audi (1).png
    - assets/viphome/image.png
    - assets/viphome/image-1.png
    - assets/viphome/image-2.png
    - assets/viphome/image-3.png
    - assets/viphome/image-4.png
    - assets/viphome/bmw.png
    - assets/viphome/image-5.png
    - assets/viphome/image-6.png
    - assets/viphome/image-7.png
    - assets/viphome/image-8.png
    - assets/viphome/image-9.png
    - assets/viphome/image-10.png
    - assets/viphome/image-11.png
    - assets/viphome/image-12.png